### ISSUE TITLE
allow KMD to accept account addresses

### ISSUE THREAD

**Issue by wisthsb1519** [algorand/go-algorand-sdk#109]
for example, ImportMultisig() takes in a public key which forces you to decode an address
https://github.com/algorand/go-algorand-sdk/blob/bc0af1afd700d7f255ae617feeb0b03040c2c2a7/client/kmd/wrappers.go#L212

python works nicely where it takes in an msig object to import a multisig account into a kmd wallet
https://github.com/algorand/py-algorand-sdk/blob/b079db660ae92d0dbf24dc04f28eb722711e426f/algosdk/kmd.py#L353

**Comment by algorotem** [comment]
algorand/java-algorand-sdk#96
