### ISSUE TITLE
HTLC Template UX

### ISSUE THREAD

**Issue by winder** [algorand/go-algorand-sdk#116]
1) Use **CloseRemainderTo**. The funds are locked in the HTLC contract account, so we can set the amount to 0 and deposit the entirety of the HTLC account with **CloseRemainderTo**.

2) Verify the preimage. We have the preImage, image and hashFn, so we are able to verify that the `hashFn(preImage) == image`: https://github.com/algorand/py-algorand-sdk/pull/71/files#diff-b0993c0c0cb44ddeecba70c5d36d57d9R211

**Comment by EvanJRichard** [comment]
Confirmed that this isn't done yet, bouncing back to ungroomed backlog
