### ISSUE TITLE
Asset ID in not PendingTransactionInformation when creating asset

### ISSUE THREAD

**Issue by rfustino** [algorand/go-algorand-sdk#166]
The Go SDK does not have the assetid in PendingTransactionInformation response, like we see in the other 3 SDKs. One needs to loop thru the assets created for this account and pluck out the highest ID value. This is how I have seen this done in the past as well as V2. Is that a sufficient way of doing it? This is probably a required feature enhancement as the other three SDKs have it. Maybe not a bug. Here is the response from python and Go. Unless I am missing it, or using the wrong call I do not see it in the response for Go. 

GO SDK response for PendingTransactionInformation
![go response for PendingTransactionInformation](https://user-images.githubusercontent.com/4959925/85433139-fd028280-b551-11ea-87ca-fafe3b25c24a.png)

Python SDK response for pending_transaction_info
![Python Response for pending_transaction_info](https://user-images.githubusercontent.com/4959925/85433197-11df1600-b552-11ea-9dfd-0b3e1684ebf7.png)

**Comment by winder** [comment]
@rfustino could you share the un-redacted go code that you're using? The AssetID is in the response object:
https://github.com/algorand/go-algorand-sdk/blob/develop/client/v2/common/models/responsemodels.go#L855

**Comment by winder** [comment]
After checking with Russ, this was a result of not calling `.Do(context.Background())`. He's writing the tutorials, so I'm sure this will be crystal clear to SDK users by the time he's finished!
