### ISSUE TITLE
Make PRs obey `make`/`golint`

### ISSUE THREAD

**Issue by EvanJRichard** [algorand/go-algorand-sdk#168]
## Summary
At time of writing there is no check that a PR obeys `golint`. Indeed, the pre-PR screen does not even mention `golint` as a requirement. As such there are linting violations throughout go-sdk, especially in the v2 client. We need to change the pre-PR prompt to mention `golint`, and make Travis enforce `golint`, as it is in `go-algorand`.

**Comment by EvanJRichard** [comment]
Moving to Icebox - PR is up as #186, but per conversation in standup, we might not want to apply this change.

**Comment by algochoi** [comment]
Replaced by https://github.com/algorand/go-algorand-sdk/issues/526
