### ISSUE TITLE
V2 Client Lacks Many Wrappers

### ISSUE THREAD

**Issue by dpaks** [algorand/go-algorand-sdk#184]
I started using v2 client of 1.4.2 release.
I found that it lacks many nice utility functions like TransactionsByAddr, TransactionByID, and many more.

Is v2 in a good shape to be used for production? If not, will v1 deprecate soon?

**Comment by dpaks** [comment]
Sorry I missed, it doesn't support algod client init with custom headers rendering purestake v2 endpoint unusable

**Comment by dpaks** [comment]
[Example](https://developer.algorand.org/docs/build-apps/connect/#create-an-algod-client) says that MakeClientWithHeaders() is available in v2 algod package but I see that it is actually present in common package [here](https://github.com/algorand/go-algorand-sdk/blob/v1.4.2/client/v2/common/common.go#L51).

**Comment by winder** [comment]
@dpaks sorry for the delay. To answer your question: you should use the v2 client, v1 is deprecated and will be removed at some point.

Thank you for noticing the missing `MakeClientWithHeaders` functions, I've created an issue for fixing that.
