### ISSUE TITLE
 I want to get the txid of each transaction in /v2/blocks/{round}, but there is no

### ISSUE THREAD

**Issue by shixiaofeia** [algorand/go-algorand-sdk#185]

**Comment by algorotem** [comment]
Hi shixiaofeia,

Many thanks for the issue. The title is a bit cut but seems like you're looking for a way to get all the txids in a specific round. 
The way to do it is using indexer v2. 
just call `https://INDEXER_URL/v2/transactions?round={round_number}`

Hope it helps!

**Comment by shixiaofeia** [comment]
Thanks for the reply, I used /v1/block/{round-number} to solve this problem

**Comment by shixiaofeia** [comment]
I hope you can help me, I want to use fast catch-up, and can reserve 100K blocks, use /v2/transactions/pending to query, how should I configure config

**Comment by shixiaofeia** [comment]
Or is it necessary to keep all archives if you want to use the indexer

**Comment by shixiaofeia** [comment]
In other words, if I want to use the indexer, I must keep the archive of all blocks, otherwise I cannot use it

**Comment by shixiaofeia** [comment]
Can I fix this error by modifying the configuration file? could not find the transaction in the transaction pool or in the last 1000 confirmed rounds ....   
I want to query transaction hashes within 100,000 blocks

**Comment by shixiaofeia** [comment]
I changed the value of CatchupBlockDownloadRetryAttempts to 50000, and then enabled fast catch-up, the synchronization time is still rising after three days
![image](https://user-images.githubusercontent.com/63829677/92340252-26ac5e00-f0ec-11ea-8783-36529db5cec3.png)

**Comment by winder** [comment]
@shixiaofeia in the future please try the community forum for node management related questions: https://forum.algorand.org/

To answer this question, you cannot use fast catchup to request a specific number of blocks. It will only retrieve the last 1000.

**Comment by winder** [comment]
You need to configure the node to use archival mode: https://developer.algorand.org/docs/run-a-node/setup/types/#archival-mode
