### ISSUE TITLE
Make similar interface for MakeAssetTransferTxn & MakePaymentTxn or correct doc

### ISSUE THREAD

**Issue by jekabolt** [algorand/go-algorand-sdk#207]
MakeAssetTransferTxn in  [https://developer.algorand.org/docs/features/asa/#transferring-an-asset](docs) is not corresponding to [https://github.com/algorand/go-algorand-sdk/blob/develop/transaction/transaction.go](implementation)
and MakeAssetTransferTxn needs implisitly convert genesis hash to base64 and MakePaymentTxn is not

**Comment by yaovi-a** [comment]
@JasonWeathersby, can you please confirm that this is a doc update? Thanks.

**Comment by algochoi** [comment]
This looks like it was closed by the [v2 Go SDK changes](https://github.com/algorand/go-algorand-sdk/pull/449) and relevant doc fixes - we no longer accept a genesis hash and instead use the SuggestedParams struct.
