### ISSUE TITLE
v2.0.0 cannot be used with `go mod` because it is not within `v2` subfolder

### ISSUE THREAD

**Issue by fabrice102** [algorand/go-algorand-sdk#221]
v2 of Go modules need to be inside a subfolder `v2` according to https://golang.org/ref/mod#major-version-suffixes
and https://blog.golang.org/v2-go-modules

Because of that, current v2.0.0 cannot be obtained using Go tools:
```bash
$ go get -u github.com/algorand/go-algorand-sdk/...@v2.0.0
go get github.com/algorand/go-algorand-sdk/...@v2.0.0: github.com/algorand/go-algorand-sdk@v2.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

(Compare with:
```bash
$ go get -u github.com/algorand/go-algorand-sdk/...@v1.8.0
go: downloading github.com/algorand/go-algorand-sdk v1.8.0
```
)

**Comment by pbennett** [comment]
Here's another writeup on the issue: https://therootcompany.com/blog/bump-go-package-to-v2/
It really depends on whether you care about compatibility with much older versions of Go (not module complaint).
If you expect go module compatibility, then it can be as simple as updating the go.mod file for the module to now be github.com/algorand/go-algorand-sdk/v2 (and tagging like it already is).
