### ISSUE TITLE
More Real-World examples

### ISSUE THREAD

**Issue by kcelestinomaria** [algorand/go-algorand-sdk#222]
Hello, I am still in confusion on how to integrate the algorand go sdk in a Go Lang App in the most lightweight way possible. Is it possible if there could be examples on calling the Algorand Go client on a handler with templates or UI in a real-world dapp? I would really love to see them so that I can connect with the sdk in the best approach in my dapp here: https://github.com/Malibia/exitor-dapp . It is simply an app where you can mint real-world assets using the Algorand Go SDK. I wanted to demonstrate with it to help developers also easily integrate with the Go SDK in a Web App without using any Javascript or any Javascript frameworks, I would really love your help. Thank you.

**Comment by winder** [comment]
There are many examples here: https://developer.algorand.org/solutions/
