### ISSUE TITLE
The transaction return this error, failed to send transaction: HTTP 400 Bad Request: {"message":"TransactionPool.Remember: tx.GenesisHash \u003cO5DUQRJSKB3WI5TEG5JTCMSCJQ2UMYKPKAZDARKHLFSXGTRXGNVQ\u003e does not match expected \u003cYBQ4JWH4DW655UWXMBF6IVUOH5WQIGMHVQ333ZFWEC22WOJERLPQ\u003e"}, how to resolve it

### ISSUE THREAD

**Issue by malingzhao** [algorand/go-algorand-sdk#239]
### Steps to reproduce

1.
2.

**Comment by winder** [comment]
You provided an incorrect genesis hash so algod rejected the transaction.

**Comment by malingzhao** [comment]
{
    "consensus-version": "https://github.com/algorandfoundation/specs/tree/abc54f79f9ad679d2d22f0fb9909fb005c16f8a1",
    "fee": 0,
    "genesis-hash": "SGO1GKSzyE7IEPItTxCByw9x8FmnrCDexi9/cOUJOiI=",
    "genesis-id": "testnet-v1.0",
    "last-round": 16383401,
    "min-fee": 1000
}

this is my params

**Comment by malingzhao** [comment]
package main

import (
	"fmt"
	"github.com/algorand/go-algorand-sdk/future"
	"io/ioutil"
	"github.com/algorand/go-algorand-sdk/crypto"
	"github.com/algorand/go-algorand-sdk/mnemonic"
	"github.com/algorand/go-algorand-sdk/types"
)

func main() {
	//account := crypto.GenerateAccount()
	//fmt.Printf("account address: %s\n", account.Address)
	//
	//m, err := mnemonic.FromPrivateKey(account.PrivateKey)
	//fmt.Printf("backup phrase = %s\n", m)
	m := "diesel hero enact funny bridge alley cupboard black own remain neck skirt desexxxxxrt hospital mask bounce pair razor unable miss spare spread fuel abstract clown"
	key, err := mnemonic.ToPrivateKey(m)
	from:="LFCOJSZXNISAVOWFGV642VUEUE3HYUJX5MBCJVIMXBNHYP5D47TOASASNQ"
	if err != nil {
		fmt.Println("the key generate the address error,", err)
	}
	// Create and sign a sample transaction using this library, *not* kmd
	// This transaction will not be valid as the example parameters will most likely not be valid
	// You can use the algod client to get suggested values for the fee, first and last rounds, and genesisID
	const fee = 1000
	const amount = 20000
	//excessive
	const firstRound = 15967591
	const lastRound = firstRound + 1000
	//failed to send transaction: HTTP 400 Bad Request: {"message":"TransactionPool.Remember: tx.GenesisHash \u003cKNDU6MKHJNJXU6KFG5EUKUCJORKHQQ2CPF3TS6BYIZWW44SDIRSQ\u003e does not match expected \u003cJBR3KGFEWPEE5SAQ6IWU6EEBZMHXD4CZU6WCBXWGF57XBZIJHIRA\u003e"}
	params := types.SuggestedParams{
		Fee:             types.MicroAlgos(fee),
		FirstRoundValid: firstRound,
		LastRoundValid:  lastRound,
		GenesisHash:     []byte("SGO1GKSzyE7IEPItTxCByw9x8FmnrCDexi9/cOUJOiI="),
		GenesisID:       "mainnet-v1.0",
	}

	tx, err := future.MakePaymentTxn(
		from, "XP6BXCH237JVVXG3GWEDZZ7Z7NRIPJMNN63UE2ZRMLIB5NRWIXUQGYRZKI",
		amount, nil, "", params,
	)
	if err != nil {
		fmt.Printf("Error creating transaction: %s\n", err)
		return
	}
	fmt.Printf("Made unsigned transaction: %+v\n", tx)
	fmt.Println("Signing transaction with go-algo-sdk library function (not kmd)")

	// Sign the Transaction
	txid, bytes, err := crypto.SignTransaction(key, tx)
	if err != nil {
		fmt.Printf("Failed to sign transaction: %s\n", err)
		return
	}

	// Save the signed object to disk
	fmt.Printf("Made signed transaction with TxID %s\n", txid)
	filename := "./signed.tx"
	err = ioutil.WriteFile(filename, bytes, 0644)

	if err != nil {
		fmt.Printf("Failed in saving transaction to file %s, error %s\n", filename, err)
		return
	}
	fmt.Printf("Saved signed transaction to file: %s\n", filename)
}


There is my Code

**Comment by malingzhao** [comment]
what is the error

**Comment by malingzhao** [comment]
I use the genesis Hash from the json get from the endpoints

**Comment by malingzhao** [comment]
Now I has found the golang sdk has many probelems , So I use the  node js sdk , the problem is resolved,

**Comment by malingzhao** [comment]
Thank you wevy much , I has use to go sdk resolve it
