### ISSUE TITLE
Excluding empty values

### ISSUE THREAD

**Issue by barnjamin** [algorand/go-algorand-sdk#269]
While comparing DryrunRequest output across multiple SDKs, I noticed Go omits some empty values that js/python do not.

Go |  JS |  Python
![image](https://user-images.githubusercontent.com/520236/145682017-3b8b8a99-66ae-4013-aa9c-b8764fcee845.png)

I'm not sure this is a bug or even important but it does make the resulting msgp output different depending on which SDK is being used.

**Comment by winder** [comment]
So far we haven't considered re-serialization as part of the API contract. In go you would have access to these objects and they would have the correct zero values. Do you think it's important that they show up in the re-serialized objects?

**Comment by barnjamin** [comment]
Not particularly, just raised it here so it was on the radar

**Comment by jasonpaulos** [comment]
Closing this because JS and Python are considered out of line here. JS is being improved in https://github.com/algorand/js-algorand-sdk/pull/862
