### ISSUE TITLE
msgpack decode masks http error

### ISSUE THREAD

**Issue by barnjamin** [algorand/go-algorand-sdk#285]
### Subject of the issue

When calling something like  `client.Block(round).Do...`, if there is an HTTP error, JSON is returned but we don't check status code and try to msgpack decode the result anyway.  

This leads to the error _seeming_ like its one with formatting and the real error is masked. 

We should check the http status code here and return an error that wraps the resulting error message https://github.com/algorand/go-algorand-sdk/blob/7285700bfe9d475535b28fbaa0f770caf3602000/client/v2/common/common.go#L220

**Comment by norunners** [comment]
What is the exact error being encountered and steps to reproduce?

**Comment by pbennett** [comment]
I see the exact same issue - ie passing a block that doesn't exist will reproduce this.  The node returns a 500 (instead of a 404 for some reason) and it comes back as a msgpack decode error.
