### ISSUE TITLE
go-algorand-sdk is unable to read a block from 3.3.x 'future' protocol (teal 6) node

### ISSUE THREAD

**Issue by pbennett** [algorand/go-algorand-sdk#288]
### Subject of the issue

Any attempt to read a Block from algod using code similar to:

```client.Block(round).Do(ctx)```

Produces the error:

```no matching struct field found when decoding stream map with key cc```

### Your environment

OSX: Using locally built (from master - w/ tealdbg PR applied) for Teal 6 development:
```
12885103145
3.3.135721.dev [algochoi/tealdbg-itxns] (commit #aefe9d57)
```

Node is being started with private network template with proto set to 'future'

**Comment by winder** [comment]
It isn't really possible for the SDKs to support "future". Features could be enabled there which are never going to be fully released (Like the compact certificate feature mentioned here).

**Comment by pbennett** [comment]
Pretty sure this was already fixed @winder - the SDK just needs to ignore unknown fields.  I believe that change went in.
