### ISSUE TITLE
Missing ParticipationUpdates struct

### ISSUE THREAD

**Issue by barnjamin** [algorand/go-algorand-sdk#305]
### Subject of the issue

When decoding a block, if the struct being decoded into does not have all the fields defined the decoder will error out. We're missing at least the ParticipationUpdates struct that is embedded in the BlockHeader

In go-algorand-sdk:
https://github.com/algorand/go-algorand-sdk/blob/3f2d85658f808232fcd8d4d4303a74f7c6171421/types/block.go#L96

In go-algorand
https://github.com/algorand/go-algorand/blob/master/data/bookkeeping/block.go#L142

**Comment by pbennett** [comment]
Thanks for this - this is a critical nasty one.

**Comment by winder** [comment]
Closed by #306
