### ISSUE TITLE
Update `MobileWrapper` branch

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/go-algorand-sdk#339]
Merge the latest changes from `develop` into `MobileWrapper` branch (used to generate iOS and Android compatible libraries).

Also, consider how to expose new functions/classes to allow ABI usage in the `MobileWrapper` branch. Specifically, as a start we want to expose the ability to create ABI method call transactions.

Looking ahead, a long-term solution to avoid an out of date `MobileWrapper` branch would be to merge it into `master`.

**Comment by algoanne** [comment]
expose multi-sig and logic-sig functions as well.
