### ISSUE TITLE
goal: command not found

### ISSUE THREAD

**Issue by ZackHayden** [algorand/go-algorand-sdk#4]
After installing the sdk...
```
go get -u github.com/algorand/go-algorand-sdk/...
```

I am getting this failure when trying to use `goal`
```
-bash: goal: command not found
```

**Comment by justicz** [comment]
Hi Zack,

This SDK is for interacting with an existing Algorand installation. Please check out https://developer.algorand.org/ for instructions on how to join TestNet (if you haven't already) and set up your node from there. That will install `goal` on your system.

Thanks!
