### ISSUE TITLE
Usage request: encryption and verification of data using crypto package

### ISSUE THREAD

**Issue by EvanJRichard** [algorand/go-algorand-sdk#53]
per discussion with @JasonWeathersby

**Comment by rotemh** [comment]
What does verification mean with respect to encryption? 
Also, can you please elaborate on the use case?

**Comment by JasonWeathersby** [comment]
This all goes to basically the same issue I had with signing and verifying bytes in the note field. I provided examples for the issue. I can not put signed bytes and the object in the notes field and decrypt it properly.

**Comment by rotemh** [comment]
It seems as if there are two different topics. Do we want to provide a way to encrypt data or to sign it (which is already provided)?

**Comment by EvanJRichard** [comment]
Result of FDE discussion: go-algorand#652 should resolve this.
