### ISSUE TITLE
JSON encoding of maps with non-string key types is invalid

### ISSUE THREAD

**Issue by joe-p** [algorand/go-algorand-sdk#558]
### Subject of the issue

When encoding a `Block`, `StateProofTracking` in `BlockHeader` is not encoded properly. 
### Your environment

github.com/algorand/go-algorand-sdk/v2 v2.0.0-20230531123858-3a0efd6a6398

### Steps to reproduce

1. Encode struct containing a `Block` using the SDKs json encoder ([example](https://github.com/joe-p/conduit-websocket-processor/blob/f38a89b129af91279ffece5425156d3ec1568382/websocket_processor.go#L93))
2. Attempt to parse JSON

### Expected behaviour

JSON is valid

### Actual behaviour

JSON is invalid

```json
{
"block": {
    "earn": 218288,
    "fees": "x/zNsljw1BicK/i21o7ml1CGQrCtAB8x/LkYw1S6hZo=",
    "frac": 6886250026,
    "gen": "mainnet-v1.0",
    "gh": "wGHE2Pwdvd7S12BL5FaOP20EGYesN73ktiC1qzkkit8=",
    "prev": "xCmYWnlpSojf4tTZU2YadEuXGnYIIXk/z1c1boljiJE=",
    "proto": "https://github.com/algorandfoundation/specs/tree/44fa607d6051730f5264526bf3c108d51f0eadb6",
    "rnd": 29701220,
    "rwcalr": 30000000,
    "rwd": "/v////////////////////////////////////////8=",
    "seed": "rInPcDh6pYvqsftiiafUypkEx03k8uGEoHTHZV/ErOE=",
    "spt": {
      0: {
        "n": 29701120
      }
    },
    "tc": 1122697227,
    "ts": 1686458129,
    "txn": "efCwo3+8txC+NwGmie+xaEO5dM/tFGrnhcrrodqhNQU=",
    "txn256": "JAaTbwP8QApV3OSv1oW5EMVShslCIiJDKIQPJM5qi+Q="
  }
}
```

Note the key under `spt` is `0`. JSON keys should be wrapped in double quotes

**Comment by algochoi** [comment]
That sounds good, I forgot that our codec repo was mega out of date.

**Comment by joe-p** [comment]
Different flavor of the same issue but posting here for clarity and posterity's sake... basically any map that has a non-string key type will not get properly encoded. This affects other maps with integer keys like local deltas, but also more complex keys. For example, `Txleases`:

```json
  "Txleases": {
      {
  "Lease": "PwvoKrpv440AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
  "Sender": "pFRedFkfkmKiIT+/WF/OEujrmHGIhB3HTP0uXHCPdKE="
}: 29701261
    }
```

**Comment by joe-p** [comment]
After looking into it a bit more https://github.com/algorand/go-codec/pull/4 will fix the encoding for numeric keys, so local deltas, createables, and spt, but there will still be a problem with encoding `Txleases`. 

From the ecnoding/json [docs](https://pkg.go.dev/encoding/json#Marshal):

> Map values encode as JSON objects. The map's key type must either be a string, an integer type, or implement encoding.TextMarshaler.

This means `Txleases` will need to implement `TextMarshaler` and `UnmarshalText`

**Comment by jasonpaulos** [comment]
cc @Eric-Warehime about the txlease issue
