### ISSUE TITLE
Balance 199000 below min 100000

### ISSUE THREAD

**Issue by algonautshant** [algorand/go-algorand-sdk#59]
$ goal asset send --amount 0 --creator CBIH...   -t PDUR...   --assetid 1 --from PDUR...  
Couldn't broadcast tx with algod: HTTP 400 Bad Request: TransactionPool.Remember: transaction S63U...: account PDUR... balance 199000 below min 100000 (1 assets)

$ goal account list
[online]	CBIH...	CBIH...	5001430048935245 microAlgos	[created assets: 1 (10 )]
	                  10          (creator CBIH..., ID 1, name )
[offline]	exampleAccount	PDUR...	200000 microAlgos	*Default

$ goal report
4295016318
1.0.49022.dev [shant/readme_changes] (commit #445b9b6d+)

Darwin Admins-MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

Genesis ID from genesis.json: privateFuture-v1

Last committed block: 11446
Time since last block: 1.6s
Sync Time: 0.0s
Last consensus protocol: future
...

**Comment by zeldovich** [comment]
Oops, indeed, the error message should be reporting the `basics.MulSaturate(eval.proto.MinBalance, ...)` value instead of just `eval.proto.MinBalance`!

**Comment by algonautshant** [comment]
Issue went away after sending an additional 1000000

**Comment by zeldovich** [comment]
We should still fix the error message to report the correct minbalance that the ledger is expecting.
