### ISSUE TITLE
go build err 

### ISSUE THREAD

**Issue by viking2015** [algorand/go-algorand-sdk#74]
go build 
# github.com/algorand/go-algorand-sdk/logic
../../../../pkg/mod/github.com/algorand/go-algorand-sdk@v0.0.0-20191031155414-fdb5215a96b5/logic/logic.go:45:28: undefined: langSpecJson

how deal this bug ？ thanks .

**Comment by pzbitskiy** [comment]
```
make build
```
or
```
go generate ./logic
go build
```

I'll update the README.

**Comment by viking2015** [comment]
My program uses go mod to reference algorand SDK，like:
go 1.13

require (
	github.com/algorand/go-algorand-sdk v0.0.0-20191031155414-fdb5215a96b5
	github.com/algorand/go-codec v1.1.7 // indirect
        ……
)

go-algorand-sdk download go mod cache dir -- 
../../../../pkg/mod/github.com/algorand/go-algorand-sdk@v0.0.0-20191031155414-fdb5215a96b5/logic/logic.go:45:28: undefined: langSpecJson

can't use make build  for logic ,how compile with go mod for my program?

**Comment by pzbitskiy** [comment]
@rotemh
