### ISSUE TITLE
How do I create an algo wallet with 12 mnemonics?

### ISSUE THREAD

**Issue by Jinxiansen** [algorand/go-algorand-sdk#82]
Hello!
When I import a wallet with `12 mnemonics`, the prompt must be 25 digits. 
Does it support 12 mnemonics? 🤔

**Comment by rotemh** [comment]
Hi @Jinxiansen,

No, our scheme of generating keys requires a 32 bytes length seed which maps to 24 words + one for checksum. 

Best
